### ISSUE TITLE
error with file uploads -- TypeError: expected a bytes-like object, NoneType found

### ISSUE THREAD

**Issue by houseofsuns** [Pylons/webtest#146] opened 2015-12-20 22:53 UTC
On my Gentoo ~amd64 machine I see the following error, when doing a
form submission with a file upload.

<pre>
    self.response = form.submit(button)
  File "/usr/lib64/python3.4/site-packages/webtest/forms.py", line 606, in submit
    params=fields, **args)
  File "/usr/lib64/python3.4/site-packages/webtest/response.py", line 294, in goto
    return method(href, **args)
  File "/usr/lib64/python3.4/site-packages/webtest/app.py", line 370, in post
    content_type=content_type)
  File "/usr/lib64/python3.4/site-packages/webtest/app.py", line 712, in _gen_request
    params, upload_files or ())
  File "/usr/lib64/python3.4/site-packages/webtest/app.py", line 525, in encode_multipart
    body = b'\r\n'.join(lines)
TypeError: sequence item 8: expected a bytes-like object, NoneType found
</pre>

I could fix this by adding the following change to encode_multipart()
in app.py. However I'm not sure this is the correct fix.

<pre>
            if value.content is not None:
                    file_info.append(value.content)
                    if value.content_type is not None:
                file_info.append(value.content_type)
        _append_file(file_info)
-            else:
+            elif value is not None:
        if isinstance(value, text_type):
                    value = value.encode('utf8')
        lines.extend([
                    b'--' + boundary,
                    b'Content-Disposition: form-data; name="' + key + b'"',

</pre>

Here is what I do: I have a form with one file upload and one submit button as follows.

```
    <form action="/event/event/1/minorform/change" method="POST" enctype="multipart/form-data" id="changeminorformform">
            <input type="file" name="minor_form" accept="application/pdf" class="form-control" >
            <button type="submit" name="submitform" class="btn btn-primary">Hochladen</button>
    </form>
```

I add a webtest.Upload for the file and submit the form with the button name as parameter. Then the variable params of encode_multipart has the value

<pre>
[('minor_form', <File name="minor_form">), ('submitform', None)]
</pre>

where the second one causes the problems.

**Comment by veelai** [comment] 2015-12-20 22:57
Some further info: I use a Gentoo unstable system with python 3.4 and webtest 2.0.18.

**Comment by benwad** [comment] 2017-04-10 14:03
I'm experiencing this error as well. Ubuntu 16.04 Python 3.5 and WebTest 2.0.27 (through django-webtest 1.9.1).

Stack trace is here:
```
Traceback (most recent call last):
  File "/home/my/project/main/projects/tests/test_admin.py", line 137, in test_add
    response = form.submit()
  File "/home/my/project/env/lib/python3.5/site-packages/webtest/forms.py", line 609, in submit
    params=fields, **args)
  File "/home/my/project/env/lib/python3.5/site-packages/webtest/response.py", line 297, in goto
    return method(href, **args)
  File "/home/my/project/env/lib/python3.5/site-packages/django_webtest/__init__.py", line 137, in post
    return super(DjangoTestApp, self).post(url, **kwargs)
  File "/home/my/project/env/lib/python3.5/site-packages/webtest/app.py", line 378, in post
    content_type=content_type)
  File "/home/my/project/env/lib/python3.5/site-packages/webtest/app.py", line 721, in _gen_request
    params, upload_files or ())
  File "/home/my/project/env/lib/python3.5/site-packages/webtest/app.py", line 534, in encode_multipart
    body = b'\r\n'.join(lines)
TypeError: sequence item 7: expected a bytes-like object, int found
```

This happens no matter what I assign to my `form['image']` field: I've tried `None`, `''` (empty string) and a file created with WebTest's `Upload`.

**Comment by gawel** [comment] 2017-04-10 14:31
Try with bytes: ```Upload(b'filename.txt', b'data', b'application/octet-stream')```

**Comment by benwad** [comment] 2017-04-10 14:39
@gawel Thanks for the quick response, but that didn't work either. Shouldn't `None` work as well? (and if not, what value should represent no file?)

**Comment by benwad** [comment] 2017-04-10 14:41
It's also worth pointing out that the form in question is in a standard Django admin view.

**Comment by gawel** [comment] 2017-04-10 14:55
Don't know for None but Upload() with bytes should definitely works (and is unit tested)

Can you debug what is in ```lines``` ?

```
  File "/home/my/project/env/lib/python3.5/site-packages/webtest/app.py", line 534, in encode_multipart
    body = b'\r\n'.join(lines)
```

**Comment by benwad** [comment] 2017-04-10 15:04
With the empty `image` field:
```
[
    b'------------a_BoUnDaRy100884688967673$',
    b'Content-Disposition: form-data; name="csrfmiddlewaretoken"',
    b'',
    b'lMHn5cMyk73bhhfhjcB2K3Fent5AiNEy5gROCketq8MR1Fe7P57He0KoXsQkcm3R',
    b'------------a_BoUnDaRy100884688967673$',
    b'Content-Disposition: form-data; name="installation_template"',
    b'',
    4,
    b'------------a_BoUnDaRy100884688967673$',
    b'Content-Disposition: form-data; name="test_set"',
    b'',
    b'',
    b'------------a_BoUnDaRy100884688967673$',
    b'Content-Disposition: form-data; name="name_nl"',
    b'',
    b'test project group NL',
    b'------------a_BoUnDaRy100884688967673$',
    b'Content-Disposition: form-data; name="name_en"',
    b'',
    b'test project group EN',
    b'------------a_BoUnDaRy100884688967673$',
    b'Content-Disposition: form-data; name="count_test"',
    b'',
    b'',
    b'------------a_BoUnDaRy100884688967673$',
    b'Content-Disposition: form-data; name="image"; filename=""',
    b'Content-Type: application/octet-stream',
    b'',
    b'',
    b'------------a_BoUnDaRy100884688967673$--',
    b''
]
```
...and with `Upload(b'filename.txt', b'data', b'application/octet-stream')`:
```
[
    b'------------a_BoUnDaRy443618985083826$',
    b'Content-Disposition: form-data; name="csrfmiddlewaretoken"',
    b'',
    b'4nS6c0vzfYwDFRfwvXtfACq2ojVgOKivok13GyavwlnT9EL1FfqR78DIcdb7uuOh',
    b'------------a_BoUnDaRy443618985083826$',
    b'Content-Disposition: form-data; name="installation_template"',
    b'',
    195,
    b'------------a_BoUnDaRy443618985083826$',
    b'Content-Disposition: form-data; name="test_set"',
    b'',
    b'',
    b'------------a_BoUnDaRy443618985083826$',
    b'Content-Disposition: form-data; name="name_nl"',
    b'',
    b'test project group NL',
    b'------------a_BoUnDaRy443618985083826$',
    b'Content-Disposition: form-data; name="name_en"',
    b'',
    b'test project group EN',
    b'------------a_BoUnDaRy443618985083826$',
    b'Content-Disposition: form-data; name="count_test"',
    b'',
    b'',
    b'------------a_BoUnDaRy443618985083826$',
    b'Content-Disposition: form-data; name="image"; filename="filename.txt"',
    b'Content-Type: application/octet-stream',
    b'',
    b'data',
    b'------------a_BoUnDaRy443618985083826$--',
    b''
]
```

**Comment by gawel** [comment] 2017-04-10 15:13
So the problem is not with the upload field but with the installation_template field which is an int. You have to convert it to a string

**Comment by benwad** [comment] 2017-04-10 15:15
@gawel Just noticed that as I saw your comment - casting it to a string works. Thanks!

The weird part was that this test worked fine before I added the upload field - I guess the encoding of the form changed and the integer was no longer accepted as a field value. Is this expected behaviour? It's quite weird that the form failed after adding a field that had nothing to do with the error.

**Comment by gawel** [comment] 2017-04-10 15:36
It's not weird, it change how the form is encoded/sent 
You just found a bug.
Looks like integers are not converted to string when enctype=mutlipart

**Comment by benwad** [comment] 2017-04-10 15:51
I see - thanks for the explanation! Is it worth opening a new issue for this bug with the integers not converting to strings or is this ticket sufficient?

**Closed** 2017-04-12 12:18 UTC

**Comment by gawel** [comment] 2017-04-12 12:20
Just fixed. Also it should raise a clever message when you use an invalid type as field value.

I'm not able to reproduce this issue but I guess it fixed it too.
